helpCmd = {
    "clac": "Calculates the provided expression\n       || Example:- calc [mathematical expression]\n       | "
            "directly put mathematical expression",
    "help":"Provides help message for every command\n       || Example:- help [command name]\n       |help",
    "admin":"This command is only for admin devices",
    "clear": "Clear's the terminal screen",
    "desk":"Minimizes everything and return to desktop",
    "ls":"List all the files in the current working directory",
    "video":"Takes a quick video",
    "pic":"Takes a quick picture",
    "mirror":"Check yourself in camera",
    "exit": "Exit's the Xenon loop",
    "restart": "Restart's the system",
    "refresh":"Clears the screen and Returns the Xenon start message",
    "fexit": "Minimizes the screen",
    "reset": "Changes the config",
    "chatgpt":"Starts a conversation with ChatGPT on the provided ChatGPT API",
    "reset-gpt-api":"Erase the provided ChatGPt API",
    "uninstall":"Safely uninstall Xenon",
    "c-server": "Close's the current running server",
    "launch": "Launch a server [the server will be launched on the Current Working Directory]",
    "files": "Check the file and folder list in current working directory",
    "goback": "Move in parent path",
    "his": "Check the command history",
    "errors": "Check the errors on malfunctioning of Xenon or any command not working",
    "ftp":"FTP Xenon provides a way to transfer your files with its own method\n       || Example:- ftp [path/name]",
    "timer": "Start's a timer\n       || Example:- timer [seconds]",
    "mini": "Minimizes the given window\n       || mini [window name]",
    "max": "Maximizes the given window\n       || Example:- max [window name]",
    "save": "Save's short notes\n       || Example:- save [note_name (one word)] [Your note (no word limit)]",
    "web": "Open's the given website\n       || Example:- web [website.com]",
    "send": "Sends message on provided time\n       || Example:- send [12:00:pm] [phone number] [Your message]",
    "search": "Searches the provided query in google.com\n       || Example:- search [your query]",
    "wiki": "Searches the provided query on wikipedia\n       || Example:- wiki [your query]",
    "find":"Search's fov the provided fie name\n       || Example:- find [-folder/-file] FolderName/FileName(filename with extention)",
    "show":"Restores a window\n       || Example:- show [window name(which is minimized)]",
    "cls":"Closes a window\n       || Example:- cls [windows name]",
    "view": "View a file\n       || Example:- view [file name [or] fil number]",
    "goto": "Change the Current Working Directory\n       || Example:- goto [file name [or] file number]",
    "cal": "Check calendar\n       || Example:- cal [for calendar of current year] [or] cal [desired year] [desired month]",
    "reminder": "Will remind you at the given time\n       || Example:- rma [12:00:pm] [reminder message]",
    "cmd":"Run shell commands\n       || Exmaple:- cmd [your commands]",
    "ss":"Take quick Screen Shot\n       || Example:-\n       |To take ss of full screen:- ss\n       |To take ss of specific window:- ss [window name]",
    "wifi":"Control wifi [can only connect to pre-connected network]\n       || Exmaple:- wifi -connect [wifi-adapter-name] [or] wifi -disable [or] wifi -list",
    "art": "Make a fancy text\n       || Example:- art [name [or] number] [your text]\n       |To check fonts: art list\n       |To see catlog: art catlog",
    "dp": "Make a quick Display Pic\n       || Example:- dp [your text]\n       |dp -catlog [number-of-images] [Text]",
    "weather":"Check weather in CLI\n       || Exmaple:-\n       |weather -temp [city/leave-to-default]\n       |weather -pressure [city/leave-to-default]\n       |weather -humidity [city/leave-to-default]\n       |weather -description [city/leave-to-default]",
    "file":"Make or remove file\n       || Example:-\n       |file -make-file [path/name](with file extension)\n       |file -make-folder [path/name]\n       |file -del-file [path/name](with extension)\n       |file -del-folder [path/name]",
    "alias":"Make a false keyword for commands\n       || Example:- alias -add [command name]\n       |alias -ls\n       |alias -del [command name]\n       |alias -reset",
    "internal":"Returns the Xenon folders\n       || Example:- internal -ss\n       |internal -video\n       |internal -pic\n       |internal -dp\n       |internal -catlog"
}